language: c
addons:
  apt:
    packages:
    - libncurses-dev
#    - linux-headers-3.13.0-40-generic
    - linux=headers-3.10.0-862.el7.x86_64

cache:
  directories:
    - $HOME/dpdk

before_install:
  - >
    [ -z "$(ls -A $HOME/dpdk)" ] &&
    cd $HOME/dpdk &&
    wget http://fast.dpdk.org/rel/dpdk-16.11.1.tar.xz &&
    tar --strip-components=1 -axvf dpdk-16.11.1.tar.xz &&
#    export RTE_KERNELDIR=/lib/modules/3.13.0-40-generic/build &&
    export /lib/modules/3.10.0-862.el7.x86_64/build/ &&
    make install T=x86_64-native-linuxapp-gcc; true

script:
  - cd $TRAVIS_BUILD_DIR
  - export RTE_SDK=$HOME/dpdk
  - export RTE_TARGET=x86_64-native-linuxapp-gcc
  - make

